using Larkins.AdventOfCode.AdventOfCode2025.Day07Laboratories;

namespace Larkins.AdventOfCode.Tests.AdventOfCode2025.Day07Laboratories;

public class Year2025Day07Part02Tests
{
    [Fact]
    public void Total_timelines()
    {
        var input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """;

        var sut = new Year2025Day07Part02Solver(input);

        var result = sut.Solve();

        result.Should().Be(40);
    }
}
