using Larkins.AdventOfCode.AdventOfCode2025.Day06TrashCompactor;
using Larkins.AdventOfCode.AdventOfCode2025.Day07Laboratories;

namespace Larkins.AdventOfCode.Tests.AdventOfCode2025.Day07Laboratories;

public class Year2025Day07Part01Tests
{
    [Fact]
    public void Tachyon_Beam_Splitter()
    {
        var input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """;

        var sut = new Year2025Day07Part01Solver(input);

        var result = sut.Solve();

        result.Should().Be(21);
    }
}
